### ISSUE TITLE
Update Everything

### ISSUE THREAD

**Issue by PSlape2** [frc-emotion/website#53]
## Photos
- [x] Update home page photos (use [BATB 2024 photos](https://photos.google.com/share/AF1QipM_MOkCaa1qVcfkRYObKF968mM0E-Da3lXAyY36JeBhVjcM8CfouiOD824U6PdwHA?key=aGpKdm1OZE8welctaXh2UjFCcVVqZDRmXzZFSjNB))
- [x] Update competition photos (as needed)
- [x] Update backdrop photos to newer photos

## Events
- [x] Add PUSD CTE 2024
- [x] Add Fairbotics to competitions
- [x] Add RBHS Bobcat Day

## Other
- [x] Add Mech-A-Mind 23673 to FTC Teams

**Comment by ArshansGithub** [comment]
Update with the new CTE 2024 event and include both the San Diego Union Tribune link and our Instagram post link
https://www.sandiegouniontribune.com/pomerado-news/news/story/2024-05-22/poway-unified-students-share-what-they-learned-through-career-technical-education-expo
Add the Del Mar fair competition but make it its own widget since we want to add that we attended with over 30 students helping to run the event and eventually we can add an Instagram link and potentially news post
Add the RBHS bobcat day and link our Instagram post and add one of the photos from the post

**Comment by ArshansGithub** [comment]
https://github.com/frc-emotion/website/pull/54
